// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhqtpdffhqyjsiwoyawb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ocXRwZGZmaHF5anNpd295YXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTA4NDksImV4cCI6MjA3NDI2Njg0OX0.xv2WviIn4S_pkVAttDUD-FTmRcYXS2zMXX_FQqiNRDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});